### ISSUE TITLE
rename to `neowaita` or `newwaita`?

### ISSUE THREAD

**Issue by iaacornus** [NeoWaita/NeoWaita#21]
Apparently, the original morewaita repo was still alive. Hence, I think it would be better if this fork would separate completely and have a different path. However, it will still sync itself with the original repo and the improvements from there. But the fork will still create its own improvements and take on different path and actions regarding some issues and changes.

**Comment by NotoriousNico** [comment]
I think renaming this fork is a good idea. From your suggestions, I like `neowaita` the most.
However, what about a name that also represents from where this fork is coming from?

Maybe something like `NeoMoreWaita`?

**Comment by iaacornus** [comment]
> I think renaming this fork is a good idea. From your suggestions, I like `neowaita` the most. However, what about a name that also represents from where this fork is coming from?
> 
> Maybe something like `NeoMoreWaita`?

yeah, that sounds better. The rename was actually suggested by the original author in the reddit post to avoid confusion:

> You're welcome to fork though. Maybe use a less confusing name.

so let's just rename it to avoid confusion and since the fork will also take on different path, like including the good looking icons that were denied/cherry picked in the original repo like #20 . these are a lot of icons and the additions look good. so yeah, once a name is settled, the repo and packages will be renamed

**Comment by iaacornus** [comment]
settled in neowaita, all references to morewaita will be changed to neowaita, but all credits and acknowledgement will also be included
