### ISSUE TITLE
Install script not working (typo in line 14)

### ISSUE THREAD

**Issue by NotoriousNico** [NeoWaita/NeoWaita#33]
I've downloaded the latest version of NeoWaita and when running the install script with either `./install.sh` or `sudo ./install.sh`, I'm getting the following errors:

```
./install.sh: line 14: shopt: extglo: invalid shell option name
./install.sh: line 15: syntax error near unexpected token `('
./install.sh: line 15: `cp -avu "$(pwd -P)"/!(*.build|*.sh|*.py|*.md|.github|.gitignore|_dev) $THEMEDIR'
```

After looking at the install script, I've found a typo in line 14, here's the fixed version (the _b_ in "extglob" was missing):

`shopt -s extglob`

Upon fixing that small typo, the install script works again.

**Comment by iaacornus** [comment]
yeah i must have removed it when i modified the script, i fixed the typo now from your suggested solution. Thank you for pointing that out, i never noticed that mistake!
